#!/usr/bin/env python3
"""Build deterministic voice-palette and additive SQL outputs from the manifest."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def sql(value: Any) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def bullets(values: list[str]) -> str:
    return "\n".join(f"* {value}" for value in values)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=ROOT / "data" / "fallout_creature_profile_manifest.json")
    parser.add_argument("--catalog", type=Path, default=ROOT / "data" / "fallout_creature_catalog.csv")
    parser.add_argument("--voices", type=Path, required=True, help="Path to Dialectic's fallout_builtin_voices.csv")
    parser.add_argument("--palette", type=Path, default=ROOT / "data" / "fallout_creature_voice_palette.json")
    parser.add_argument("--sql", type=Path, default=ROOT / "data" / "fallout_creature_bio_templates.sql")
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    with args.catalog.open("r", encoding="utf-8-sig", newline="") as handle:
        catalog = list(csv.DictReader(handle))
    with args.voices.open("r", encoding="utf-8-sig", newline="") as handle:
        voice_rows = list(csv.DictReader(handle))
    voice_by_id = {row["voicetype"].strip().lower(): row for row in voice_rows}

    assigned = sorted({row["voiceid"].lower() for row in manifest["profiles"]})
    unknown = [voice for voice in assigned if voice not in voice_by_id]
    if unknown:
        raise RuntimeError(f"Unknown assigned voices: {', '.join(unknown)}")
    palette = {
        "catalog": manifest["catalog"],
        "validation": "catalog_sample_validated_not_ingame_auditioned",
        "voices": [
            {
                "voiceid": voice,
                "sample": voice_by_id[voice]["voicefile"],
                "sample_transcript": voice_by_id[voice]["transcript"],
            }
            for voice in assigned
        ],
    }
    args.palette.write_text(json.dumps(palette, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")

    profile_by_id = {row["template_name"].removeprefix("creature_"): row for row in manifest["profiles"]}
    included = [row for row in catalog if row["classification"] == "include_nonverbal"]
    all_name_profiles: dict[str, set[str]] = defaultdict(set)
    excluded_names: set[str] = set()
    for row in catalog:
        name = row["display_name"].strip().casefold()
        if not name:
            continue
        if row["classification"] == "include_nonverbal":
            all_name_profiles[name].add(row["profile_id"])
        else:
            excluded_names.add(name)
    safe_names = {name for name, profiles in all_name_profiles.items() if len(profiles) == 1 and name not in excluded_names}

    lines = [
        "-- Generated by tools/build_fallout_creature_seed.py. Do not edit by hand.",
        "-- Additive official TTW non-verbal creature profiles and stable actor mappings.",
        "BEGIN;",
        "",
    ]
    template_values = []
    for row in manifest["profiles"]:
        profile = row["profile"]
        template_values.append("(" + ",".join([
            sql(row["template_name"]), sql("fallout,creature," + row["species_or_variant"].lower().replace(" ", "_")),
            sql(profile["core"]), sql(profile["npc_static_bio"]), sql(profile["appearance"]), sql(profile["personality"]),
            sql(json.dumps(profile["relationships"], ensure_ascii=False, separators=(",", ":"))), sql(profile["occupation"]),
            sql(bullets(profile["skills"])), sql(profile["speechstyle"]), sql(bullets(profile["goals"])),
            sql(row["voiceid"].lower()), "NULL", sql(row["species_or_variant"]), "NULL",
        ]) + ")")
    lines.extend([
        "INSERT INTO public.bio_templates (npc_name,worldknowledge_tags,core,npc_static_bio,appearance,personality,relationships,occupation,skills,speechstyle,goals,voiceid,gender,race,refid) VALUES",
        ",\n".join(template_values),
        "ON CONFLICT (npc_name) DO UPDATE SET",
        " worldknowledge_tags=EXCLUDED.worldknowledge_tags, core=EXCLUDED.core, npc_static_bio=EXCLUDED.npc_static_bio,",
        " appearance=EXCLUDED.appearance, personality=EXCLUDED.personality, relationships=EXCLUDED.relationships,",
        " occupation=EXCLUDED.occupation, skills=EXCLUDED.skills, speechstyle=EXCLUDED.speechstyle, goals=EXCLUDED.goals,",
        " voiceid=EXCLUDED.voiceid, gender=EXCLUDED.gender, race=EXCLUDED.race, refid=EXCLUDED.refid;",
        "",
    ])
    mapping_values = []
    for row in included:
        plugin, local_formid = row["stable_identity"].split("|", 1)
        exact_name = row["display_name"].strip() if row["display_name"].strip().casefold() in safe_names else None
        mapping_values.append("(" + ",".join([
            sql("creature_" + row["profile_id"]), sql(plugin), sql(local_formid.upper()), "NULL", "NULL", sql(exact_name), "TRUE",
        ]) + ")")
    lines.extend([
        "INSERT INTO public.bio_template_actor_map (template_name,base_plugin,base_local_formid,reference_plugin,reference_local_formid,exact_name,is_nonverbal_creature) VALUES",
        ",\n".join(mapping_values),
        "ON CONFLICT (template_name,base_plugin,base_local_formid,COALESCE(reference_plugin,''),COALESCE(reference_local_formid,'')) DO UPDATE SET",
        " exact_name=EXCLUDED.exact_name, is_nonverbal_creature=EXCLUDED.is_nonverbal_creature;",
        "",
        "COMMIT;",
        "",
    ])
    args.sql.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(json.dumps({"profiles": len(template_values), "mappings": len(mapping_values), "voices": len(assigned), "safe_name_fallbacks": len(safe_names)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
