-- Additive and repeatable for both new and existing installations. Built-ins live in code.
CREATE TABLE IF NOT EXISTS public.global_settings_presets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(60) NOT NULL CHECK (length(btrim(name)) > 0),
    snapshot jsonb NOT NULL CHECK (jsonb_typeof(snapshot) = 'object'),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS global_settings_presets_name_unique
    ON public.global_settings_presets (lower(name));
